package kz.testcenter.app.appealent.utils.constants;

public class DBFunctionNumberOfFieldsConstant {

    public static final int NUMBER_OF_RETURN_FIELDS_OF_GET_APPEAL_LIST_FUNCTION = 58;
    public static final int NUMBER_OF_RETURN_FIELDS_OF_GET_APPEAL_BY_ID_FUNCTION = 12;
    public static final int NUMBER_OF_RETURN_FIELDS_OF_GET_APPEAL_RESULT_DESCRIPTION_FILE_FUNCTION = 2;
    public static final int NUMBER_OF_RETURN_FIELDS_OF_GET_APPEAL_RESULT_DESCRIPTION_FILE_BY_FILE_ID_FUNCTION = 2;
    public static final int NUMBER_OF_RETURN_FIELDS_OF_GET_APPEAL_RESULT_DESCRIPTION_LIST_BY_QUESTION_ID_FUNCTION = 11;
    public static final int NUMBER_OF_RETURN_FIELDS_OF_GET_APPEAL_STATISTIC_BY_QUESTION_FUNCTION = 59;
    public static final int NUMBER_OF_RETURN_FIELDS_OF_GET_APPEAL_STATISTIC_BY_QUESTION_ID_FUNCTION = 51;
    public static final  int NUMBER_OF_RETURN_FIELDS_OF_GET_APPEAL_UPLOAD_FILE_FUNCTION = 4;
    public static final int NUMBER_OF_RETURN_FIELDS_OF_GET_EXPERT_SUBJECT_LIST_FUNCTION = 14;
    public static final int NUMBER_OF_RETURN_FIELDS_OF_GET_STUDENT_APPEAL_FUNCTION = 18;
    public static final int NUMBER_OF_RETURN_FIELDS_OF_GET_STUDENT_APPEAL_UPLOAD_FILE_FUNCTION = 6;

}
