package kz.testcenter.app.appealent.utils.constants;

public class DBFunctionFieldsNameConstant {

    public static final String IN_TEST_TYPE_ID_FIELD = "in_test_type_id";
    public static final String IN_START_DATE_FIELD = "in_start_date";
    public static final String IN_FINISH_DATE_FILED = "in_finish_date";
    public static final String IN_END_DATE_FIELD = "in_end_date";
    public static final String IN_EXPERT_ID_FIELD = "in_expert_id";
    public static final String IN_SUBJECT_ID_FIELD = "in_subject_id";
    public static final String IN_LANG_ID_FIELD = "in_lang_id";
    public static final String IN_APPEAL_TYPE_ID_FIELD = "in_appeal_type_id";
    public static final String IN_APPEAL_STATUS_TYPE_IDS_FIELD = "in_appeal_status_type_ids";
    public static final String IN_ORDER_LIST_FIELDS_FIELD = "in_order_list_fields";
    public static final String IN_USER_ROLE_TYPE_ID_FIELD = "in_user_role_type_id";
    public static final String IN_COMMISSION_MEMBER_TYPE_ID_FIELD = "in_commission_member_type_id";
    public static final String IN_MID_FIELD = "in_mid";

    public static final String IN_APPEAL_ID_FIELD = "in_appeal_id";
    public static final String IN_TEST_SERVER_ID_FIELD = "in_test_server_id";
    public static final String IN_CRYPT_KEY_FIELD = "in_crypt_key";
    public static final String IN_FILE_ID_FIELD = "in_file_id";
    public static final String IN_ORIGINAL_QUESTION_ID_FIELD = "in_original_question_id";

    public static final String OUT_SUBJECT_ID_FIELD = "out_subject_id";
    public static final String OUT_SUBJECT_NAME_KAZ_FIELD = "out_subject_name_kaz";
    public static final String OUT_SUBJECT_NAME_RUS_FIELD = "out_subject_name_rus";
    public static final String OUT_LANG_NAME_KAZ_FIELD = "out_lang_name_kaz";
    public static final String OUT_LANG_NAME_RUS_FIELD = "out_lang_name_rus";
    public static final String OUT_CNT_QUESTION_ALL_FIELD = "out_cnt_question_all";
    public static final String OUT_CNT_QUESTION_ALL_UDOV_FIELD = "out_cnt_question_all_udov";
    public static final String OUT_CNT_QUESTION_ALL_NEUDOV_FIELD = "out_cnt_question_all_neudov";
    public static final String OUT_CNT_QID_CONTENT_ALL_FIELD = "out_cnt_qid_content_all";
    public static final String OUT_CNT_QID_TECH_ALL_FIELD = "out_cnt_qid_tech_all";
    public static final String OUT_CNT_QID_UDOV_CONTENT_FIELD = "out_cnt_qid_udov_content";
    public static final String OUT_CNT_QID_UDOV_TECH_FIELD = "out_cnt_qid_udov_tech";
    public static final String OUT_CNT_QID_NEUDOV_CONTENT_FIELD = "out_cnt_qid_neudov_content";
    public static final String OUT_CNT_QID_NEUDOV_TECH_FIELD = "out_cnt_qid_neudov_tech";
    public static final String OUT_CNT_APPEAL_ALL_FIELD = "out_cnt_appeal_all";
    public static final String OUT_CNT_CONTENT_ALL_FIELD = "out_cnt_content_all";
    public static final String OUT_CNT_TECH_ALL_FIELD = "out_cnt_tech_all";
    public static final String OUT_CNT_FINISH_ALL_FIELD = "out_cnt_finish_all";
    public static final String OUT_CNT_FINISH_CONTENT_FIELD = "out_cnt_finish_content";
    public static final String OUT_CNT_FINISH_TECH_FIELD = "out_cnt_finish_tech";
    public static final String OUT_CNT_NONE_ALL_FIELD = "out_cnt_none_all";
    public static final String OUT_CNT_NONE_CONTENT_FIELD = "out_cnt_none_content";
    public static final String OUT_CNT_NONE_TECH_FIELD = "out_cnt_none_tech";
    public static final String OUT_CNT_RASPRED_FIELD = "out_cnt_raspred";
    public static final String OUT_CNT_RASPRED_CONTENT_FIELD = "out_cnt_raspred_content";
    public static final String OUT_CNT_RASPRED_TECH_FIELD = "out_cnt_raspred_tech";
    public static final String OUT_CNT_WORK_FIELD = "out_cnt_work";
    public static final String OUT_CNT_WORK_CONTENT_FIELD = "out_cnt_work_content";
    public static final String OUT_CNT_WORK_TECH_FIELD = "out_cnt_work_tech";
    public static final String OUT_CNT_PRED_FIELD = "out_cnt_pred";
    public static final String OUT_CNT_PRED_CONTENT_FIELD = "out_cnt_pred_content";
    public static final String OUT_CNT_PRED_TECH_FIELD = "out_cnt_pred_tech";
    public static final String OUT_CNT_PREDEND_FIELD = "out_cnt_predend";
    public static final String OUT_CNT_PREDEND_CONTENT_FIELD = "out_cnt_predend_content";
    public static final String OUT_CNT_PREDEND_TECH_FIELD = "out_cnt_predend_tech";
    public static final String OUT_CNT_PREDBACK_FIELD = "out_cnt_predback";
    public static final String OUT_CNT_PREDBACK_CONTENT_FIELD = "out_cnt_predback_content";
    public static final String OUT_CNT_PREDBACK_TECH_FIELD = "out_cnt_predback_tech";
    public static final String OUT_CNT_NEUDOV_FIELD = "out_cnt_neudov";
    public static final String OUT_CNT_NEUDOV_CONTENT_FIELD = "out_cnt_neudov_content";
    public static final String OUT_CNT_NEUDOV_TECH_FIELD = "out_cnt_neudov_tech";
    public static final String OUT_CNT_PREV_UDOV_ALL_FIELD = "out_cnt_prev_udov_all";
    public static final String OUT_CNT_PREV_UDOV_CONTENT_FIELD = "out_cnt_prev_udov_content";
    public static final String OUT_CNT_PREV_UDOV_TECH_FIELD = "out_cnt_prev_udov_tech";
    public static final String OUT_CNT_PREV_UDOV_ONE_FIELD = "out_cnt_prev_udov_one";
    public static final String OUT_CNT_PREV_UDOV_ONE_CONTENT_FIELD = "out_cnt_prev_udov_one_content";
    public static final String OUT_CNT_PREV_UDOV_ONE_TECH_FIELD = "out_cnt_prev_udov_one_tech";
    public static final String OUT_CNT_PREV_UDOV_TWO_FIELD = "out_cnt_prev_udov_two";
    public static final String OUT_CNT_PREV_UDOV_TWO_CONTENT_FIELD = "out_cnt_prev_udov_two_content";
    public static final String OUT_CNT_PREV_UDOV_TWO_TECH_FIELD = "out_cnt_prev_udov_two_tech";
    public static final String OUT_CNT_UDOV_ALL_FIELD = "out_cnt_udov_all";
    public static final String OUT_CNT_UDOV_CONTENT_FIELD = "out_cnt_udov_content";
    public static final String OUT_CNT_UDOV_TECH_FIELD = "out_cnt_udov_tech";
    public static final String OUT_CNT_UDOV_ONE_FIELD = "out_cnt_udov_one";
    public static final String OUT_CNT_UDOV_ONE_CONTENT_FIELD = "out_cnt_udov_one_content";
    public static final String OUT_CNT_UDOV_ONE_TECH_FIELD = "out_cnt_udov_one_tech";
    public static final String OUT_CNT_UDOV_TWO_FIELD = "out_cnt_udov_two";
    public static final String OUT_CNT_UDOV_TWO_CONTENT_FIELD = "out_cnt_udov_two_content";
    public static final String OUT_CNT_UDOV_TWO_TECH_FIELD = "out_cnt_udov_two_tech";

}
